name: vitalsync
description: "VitalSync â€” Health & Fitness Companion. Medication reminders,
  symptom tracking, workout logging, progress analysis, and cross-module
  insights."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  cached_network_image: ^3.4.1
  cloud_firestore: ^6.1.2
  collection: ^1.19.1
  connectivity_plus: ^7.0.0
  cupertino_icons: ^1.0.8
  drift: ^2.23.1
  dynamic_color: ^1.7.0
  equatable: ^2.0.7
  firebase_analytics: ^12.1.2
  firebase_auth: ^6.1.4
  firebase_core: ^4.4.0
  fl_chart: ^1.1.1
  flutter:
    sdk: flutter
  flutter_local_notifications: ^20.1.0
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^3.2.1
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.17
  get_it: ^9.2.0
  go_router: ^17.1.0
  injectable: ^2.5.0
  intl: ^0.20.2
  json_annotation: ^4.9.0
  logger: ^2.5.0
  path: ^1.9.1
  path_provider: ^2.1.5
  riverpod_annotation: ^4.0.2
  rxdart: ^0.28.0
  shared_preferences: ^2.5.2
  shimmer: ^3.0.0
  sqlite3_flutter_libs: ^0.5.28
  table_calendar: ^3.1.3
  timezone: ^0.10.0
  uuid: ^4.5.1
  workmanager: ^0.9.0+3
  share_plus: ^12.0.1
  vibration: ^3.1.6
  confetti: ^0.8.0
  flutter_animate: ^4.5.0

dev_dependencies:
  bloc_test: ^10.0.0

  # --- Code Generation ---
  build_runner: ^2.4.14
  drift_dev: ^2.23.1

  # --- Linting ---
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.7.0
  json_serializable: ^6.9.4

  # --- Testing ---
  mocktail: ^1.0.4
  riverpod_generator: ^4.0.3

flutter:
  uses-material-design: true
  generate: true
